---

- name: create gomplate directories
  file:
    owner: root
    group: root
    path: "{{ item }}"
    state: directory
    mode: 0755
  with_items:
    - "/opt/gomplate"
    - "/opt/gomplate/bin"

- name: download gomplate
  get_url:
    url: "{{ gomplate_url_binary }}"
    dest: "/opt/gomplate/bin/gomplate"
    # checksum: "sha512:{{ gomplate_url_binary_checksum }}"
    owner: root
    group: root
    mode: 755
    setype: bin_t
    seuser: system_u
  changed_when: false

- name: link aws cli
  ansible.builtin.file:
    src: "/opt/gomplate/bin/gomplate"
    dest: /usr/bin/gomplate
    mode: 755
    owner: root
    group: root
    state: link
