---
- name: create gomplate directories
  ansible.builtin.file:
    owner: root
    group: root
    path: "{{ item }}"
    state: directory
    mode: "0755"
  with_items:
    - /opt/gomplate
    - /opt/gomplate/bin

- name: download gomplate
  ansible.builtin.get_url:
    url: "{{ gomplate_url_binary }}"
    dest: /opt/gomplate/bin/gomplate
    # checksum: "sha512:{{ gomplate_url_binary_checksum }}"
    owner: root
    group: root
    mode: "0755"
    setype: bin_t
    seuser: system_u

- name: link gomplate
  ansible.builtin.file:
    src: /opt/gomplate/bin/gomplate
    dest: /usr/bin/gomplate
    mode: "0755"
    owner: root
    group: root
    state: link
